name: "dzil build & multitest"
on: push

jobs:
  build-tarball:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Install cpanminus
        run: |
          curl https://cpanmin.us/ > /tmp/cpanm
          chmod u+x /tmp/cpanm
      - name: Install Dist::Zilla
        run: sudo apt-get install -y libdist-zilla-perl
      - name: Build tarball
        run: |
          dzil authordeps --missing | /tmp/cpanm --notest -S
          dzil listdeps --author --missing | /tmp/cpanm --notest -S
          dzil build
          mv Test-Deep-*.tar.gz Test-Deep.tar.gz
      - name: Upload tarball
        uses: actions/upload-artifact@v3
        with:
          name: Test-Deep.tar.gz
          path: Test-Deep.tar.gz

  multiperl-test:
    needs: build-tarball
    env:
      # some plugins still needs this to run their tests...
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          # - 'latest'
          - '5.28'
          # - '5.26'
          # - '5.24'
          # - '5.22'
          # - '5.20'
          # - '5.18'
          # - '5.16'
          # - '5.14'
          # - '5.12'
          # - '5.10'
          # - '5.8'

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
      - name: Download tarball
        uses: actions/download-artifact@v3
        with:
          name: Test-Deep.tar.gz
      - name: Extract tarball
        run: tar zxvf Test-Deep.tar.gz
      - name: Install dependencies
        run: |
          cd Test-Deep-1*
          cpanm --installdeps --notest .
      - name: Makefile.PL
        run: |
          cd Test-Deep-1*
          perl Makefile.PL
      - name: Run the tests
        run: |
          cd Test-Deep-1*
          make test

