name: "dzil build & multitest"
on: push

jobs:
  build-tarball:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Install cpanminus
        run: |
          curl https://cpanmin.us/ > /tmp/cpanm
          chmod u+x /tmp/cpanm
      - name: Install Dist::Zilla
        run: sudo apt-get install -y libdist-zilla-perl
      - name: Build tarball
        run: |
          dzil authordeps --missing | /tmp/cpanm --notest -S
          dzil listdeps --author --missing | /tmp/cpanm --notest -S
          dzil build
          mv Test-Deep-*.tar.gz Test-Deep.tar.gz
      - name: Upload tarball
        uses: actions/upload-artifact@v3
        with:
          name: Test-Deep.tar.gz
          path: Test-Deep.tar.gz

